### ISSUE TITLE
I can't set target element

### ISSUE THREAD

**Issue by juancarlosestradanieto** [Choicelin/vue-load-script-plus#2]
I can't set target element.
I need those scripts to load after some content, indeed, I need them to load before the body tag closes, but they are added by default inside the head.

This is the first time I create an issue, for that excuse me if it is not the right place for this.

Grettings.

**Comment by Choicelin** [comment]
ok，I get it. Sorry for missing your issue, I will fix it soon

**Comment by Choicelin** [comment]
The 1.6.6 version will solve it ,and it has published!
